baseURL = "http://dev.kaplonski.pl/"
languageCode = "pl"
title = "kaplonski.pl"
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "slaweq"
  TwitterID = "slawqo"
  LinkedInID = "sławomir-kapłoński-0aaa0770"
  Name = "Slawek Kaplonski"
  HeaderUsername = "slawek"
  HeaderHostname = "homepage"
  Email = "slawek@kaplonski.pl"
  About = "I'm software engineer from Wroclaw in Poland. I love programming in Python and SDN solutions. Since few years I'm active OpenStack contributor."
  ProfilePicture = "/images/me.JPG"
