baseURL = "http://kaplonski.pl/"
languageCode = "pl"
title = "kaplonski.pl"
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "about_me"
    weight = 1
    url = "/about"

[params]
  TwitterID = "slaweq"
  GithubID = "slawqo"
  FacebookID = "slawek.kaplonski"
  LinkedInID = "sławomir-kapłoński-0aaa0770"
  Name = "Slawek Kaplonski"
  HeaderUsername = "slawek"
  HeaderHostname = "homepage"
  About = "I'm software engineer from Wroclaw in Poland. I love Linux, programming in Python and exploring SDN solutions. Since few years I'm active OpenStack contributor."
  ProfilePicture = "/images/me.JPG"
